### ISSUE TITLE
clarify the handling of compiling a whole directory vs having to scan for source files

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-gradle-plugin#1]
we should only scan for frege files when no source directory is given - in which case the compiler is anyway figuring that out and we avoid the duplication work. Another issue here is the gradle logic for detecting changes that require re-build. Gradle takes a lot more into consideration than the frege compiler, e.g. changes in the settings.

**Comment by Ingo60** [comment]
In case of changes in the settings (like, the user suddenly wants -O, but there already artifacts compiled without -O), I suggest cleaning the destination (classes) folder. This will by necessity force a full rebuild.

The frege compiler does not care if half of the code is compiled with -O and the other half without -O. This is true for almost all options, except maybe for pathological class-path changes that would introduce two different java classes with the same (external) name.

**Comment by Dierk** [comment]
ok, thanks. Resolved in commit #4f32ab3
