### ISSUE TITLE
Repository description is misleading

### ISSUE THREAD

**Issue by mperry** [Frege/frege-gradle-plugin#10]
The current description is `Spice up your Groovy projects with some Frege`.  This is misleading as it applies to more than Groovy projects.

Suggest changing the description to: `Gradle plugin for compiling Frege projects`.

**Comment by Dierk** [comment]
Hm, it appears I'm not allowed to change that. Ingo?

**Comment by Ingo60** [comment]
I can look at it only tomorrow. Will change the text according to Mark, if
possible.

**Comment by Ingo60** [comment]
Done.
