### ISSUE TITLE
make proper use of source sets

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-gradle-plugin#15]
source sets are used for
- proper detection of source code changes that need recompilation
- tooling API can expose to IDEs what directories are considered source dirs
- allows reconfiguration of where the Frege sources are following the structure as other plugins (Java, Groovy)
- packaging tasks may rely on it.

**Comment by Dierk** [comment]
I started to work on this issue in the SourceSet branch, following the approach of the golo-lang plugin.

**Comment by breskeby** [comment]
I added some integration test coverage for this. I'd consider this issue as resolved for now

**Comment by Dierk** [comment]
awesome. cool to see the integration tests. now even I know how to write those! :-)
This is addressing an issue that always bugged me.Thanks a lot!

**Comment by breskeby** [comment]
FYI: I made use of TestKit here which is a quite new feature in Gradle to do integration testing of build and plugin code. To use the latest TestKit functionality, the plugin build requires a recent Gradle version as TestKit is under active development. It also allows to test the plugin against different Gradle versions. The plugin itself should work with everything gradle > 2.0 I think. At one point we might want full integTest coverage for this but it requires some more test inrastructure code I guess to make this convenvient,

**Comment by Dierk** [comment]
I'm a bit concerned with the Gradle versions. It appears that frequent version changes and having too many Frege projects with different versions is not appreciated by the community. I for myself have no issues with this but we sometimes have to care for users with less bandwidth.

We are currently at 2.7 for most projects and try to settle on that.
So, if possible, this would be preferred.

As a side note:
Gradle is progressing really fast. That has many benefits and when talking to Hans on the subject he mentioned that many important users want to have it like so.  For us, the 6-week cycle is too fast. We will most likely not upgrade to every new version for the simple reason of download size.
(Just to give the gradle team an "opposite" data point ;-))
