### ISSUE TITLE
why fregedoc doesn't generate a fregedoc.html ?

### ISSUE THREAD

**Issue by januslynd** [Frege/frege-gradle-plugin#32]
Hi I'm generating my project's fregedoc with the gradle plugin, but no framedoc.html is created (like the one at http://www.frege-lang.org/doc/fregedoc.html)
- Am I missing something ? Some parameter...
- Is this a bug ?

Thanks :)

**Comment by Ingo60** [comment]
No, its not a bug, IMHO.
This is done by an extra tool `frege.tools.MakeDocIndex` that should be included in the fregec.jar

**Comment by januslynd** [comment]
Agree, it's not a bug of the Gradle plugin. I just assumed `frege.tools.fregeDoc` tool should be doing everything for me (the same way javadoc does) :(

In the meantime, as a workaround, I would probably create a Gradle task to invoke `MakeDocIndex` after invoking `fregeDoc` task.

Thanks

PD: It's ok for me to close this issue.
