### ISSUE TITLE
Plugin is broken on Gradle 2.12

### ISSUE THREAD

**Issue by ysb33r** [Frege/frege-gradle-plugin#35]
This is directly related to the change in Gradle's internal API  class `DefaultSourceDirectorySet`. The fix for this would be similar to https://github.com/ysb33r/gradle-mirah-plugin/blob/master/src/main/groovy/org/ysb33r/gradle/mirah/MirahSourceSet.groovy#L69

**Comment by breskeby** [comment]
thanks for the report. fixed on master,
