### ISSUE TITLE
Clarification about pre-requisites

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-gradle-plugin#6]
Since this will be used by people that are not familiar with groovy/gradle, would it be in order to state the pre-requisites for running gradlew?

I just `sudo apt-get installed`  groovy and gradle (worth 150++MB, and probably totally outdated?), just to see that gradlew fetches a "gradle-2.3-all.zip"

**Comment by Dierk** [comment]
interestingly, the only prerequisite is to have some version of Java.
The rest is self-installing.
That may be worth mentioning, though.

Dierk

sent from:mobile

**Comment by Ingo60** [comment]
It wouldn't be an issue if this was done for gradle/groovy fans only.
But since you are going to use this in your projects, people are exposed to it that do not know this.

BTW, the gradle-plugin fetches a gradle-2.3-all.zip, and then, when I fecth your frepl-gui project, it fetches another one:

```
ingo@obonto:~$ find .gradle -type f -name gradle -print
.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm/gradle-2.3/bin/gradle
.gradle/wrapper/dists/gradle-2.3-all/w01pvxy5gty3tegjrai84pm3/gradle-2.3/bin/gradle
```

**Comment by Dierk** [comment]
> It wouldn't be an issue if this was done for gradle/groovy fans only.

Well, the Gradle plugin is for Gradle users (and Gradle uses Groovy).

The maven tile is for maven users, the leinigen plugin for leinigen users.
Some may prefer to have no build systems at all.
Everyone can have their favorite pick.

> But since you are going to use this in your projects, people are exposed to it that do not know this.

When I use it in my projects and ppl want to compile, then it is easiest to follow my pick of build system.
But they are in no way forced to do so. They can just refer to published artefacts from within their own favorite build system.

For the user of let's say the reply-gui, they never have to build themselves. They just start java -jar ...

> BTW, the gradle-plugin fetches a gradle-2.3-all.zip, and then, when I fecth your frepl-gui project, it fetches another one:
> 
> ingo@obonto:~$ find .gradle -type f -name gradle -print
> .gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm/gradle-2.3/bin/gradle
> .gradle/wrapper/dists/gradle-2.3-all/w01pvxy5gty3tegjrai84pm3/gradle-2.3/bin/gradle

Interesting. They have different hashes. Maybe they come from different repos?

cheers
Dierk

**Comment by Ingo60** [comment]
Fine, gradually I learn more and more, but can we not document this somewhere?

I mean, just in case some bloody newbee like me comes along? One line on the front page like: you don' t need to download/install this yourself. 

I mean, the current README somehow suggests one should install this locally?

This would perhaps not as important if it would just work. Which is, unfortunately, not the case:
- there is no frege-repl on sonatype or elsewhere, instead, as I had to find out by trial and error, one must build its own prior to using the gradle-plugin or any project that uses it. Is this not worth mentioning?
- Plus, the artifact id of the repl is not frege, but org.frege-lang
- Mark's native-gen apparently is compiled with Java8. No idea if this is by accident or intensional, but in the latter case this too should be mentioned.

**Comment by Dierk** [comment]
Extended the readme.
