### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-gradle-plugin#7]
Here is what I did:

```
$  git clone https://github.com/Frege/frege-gradle-plugin.git
$ cd frege-gradle-plugin
$ $SHELL gradlew
Downloading http://services.gradle.org/distributions/gradle-2.3-all.zip ...
Unzipping /home/ingo/.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm/gradle-2.3-all.zip to /home/ingo/.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm
Set executable permissions for: /home/ingo/.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm/gradle-2.3/bin/gradle
:compileJava UP-TO-DATE
:compileGroovy
Download https://oss.sonatype.org/content/groups/public/com/github/mperry/frege/native-gen/0.1-SNAPSHOT/native-gen-0.1-20150217.161146-1.pom

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find com.theoryinpractise.frege:frege:3.22.367-g2737683-g2737683.
  Searched in the following locations:
  https://repo1.maven.org/maven2/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.pom
  https://repo1.maven.org/maven2/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.jar
  file:/home/ingo/.m2/repository/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.pom
  file:/home/ingo/.m2/repository/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.jar
  https://oss.sonatype.org/content/groups/public/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.pom
  https://oss.sonatype.org/content/groups/public/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.jar
  Required by:
    org.frege-lang:frege-gradle-plugin:0.1-SNAPSHOT
> Could not find frege:frege-repl-core:1.1.1-SNAPSHOT.
  Searched in the following locations:
  https://repo1.maven.org/maven2/frege/frege-repl-core/1.1.1-SNAPSHOT/maven-metadata.xml
  https://repo1.maven.org/maven2/frege/frege-repl-core/1.1.1-SNAPSHOT/frege-repl-core-1.1.1-SNAPSHOT.pom
  https://repo1.maven.org/maven2/frege/frege-repl-core/1.1.1-SNAPSHOT/frege-repl-core-1.1.1-SNAPSHOT.jar
  file:/home/ingo/.m2/repository/frege/frege-repl-core/1.1.1-SNAPSHOT/maven-metadata.xml
  file:/home/ingo/.m2/repository/frege/frege-repl-core/1.1.1-SNAPSHOT/frege-repl-core-1.1.1-SNAPSHOT.pom
  file:/home/ingo/.m2/repository/frege/frege-repl-core/1.1.1-SNAPSHOT/frege-repl-core-1.1.1-SNAPSHOT.jar
  https://oss.sonatype.org/content/groups/public/frege/frege-repl-core/1.1.1-SNAPSHOT/maven-metadata.xml
  https://oss.sonatype.org/content/groups/public/frege/frege-repl-core/1.1.1-SNAPSHOT/frege-repl-core-1.1.1-SNAPSHOT.pom
  https://oss.sonatype.org/content/groups/public/frege/frege-repl-core/1.1.1-SNAPSHOT/frege-repl-core-1.1.1-SNAPSHOT.jar
Required by:
  org.frege-lang:frege-gradle-plugin:0.1-SNAPSHOT
> Could not find com.theoryinpractise.frege:frege:3.22.367-g2737683-g2737683.
  Searched in the following locations:
  https://repo1.maven.org/maven2/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.pom
  https://repo1.maven.org/maven2/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.jar
  file:/home/ingo/.m2/repository/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.pom
  file:/home/ingo/.m2/repository/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.jar
  https://oss.sonatype.org/content/groups/public/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.pom
  https://oss.sonatype.org/content/groups/public/com/theoryinpractise/frege/frege/3.22.367-g2737683-g2737683/frege-3.22.367-g2737683-g2737683.jar
  Required by:
  org.frege-lang:frege-gradle-plugin:0.1-SNAPSHOT > com.github.mperry.frege:native-gen:0.1-SNAPSHOT
```

**Comment by Dierk** [comment]
> $  git clone https://github.com/Frege/frege-gradle-plugin.git
> $ cd frege-gradle-plugin
> $ $SHELL gradlew
> Downloading http://services.gradle.org/distributions/gradle-2.3-all.zip ...
> Unzipping /home/ingo/.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm/gradle-2.3-all.zip to /home/ingo/.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm
> Set executable permissions for: /home/ingo/.gradle/wrapper/dists/gradle-2.3-all/4tufdqhiljn0o29rj6b3hvc6qm/gradle-2.3/bin/gradle
> :compileJava UP-TO-DATE
> :compileGroovy
> so far so good
> Download https://oss.sonatype.org/content/groups/public/com/github/mperry/frege/native-gen/0.1-SNAPSHOT/native-gen-0.1-20150217.161146-1.pom
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Could not resolve all dependencies for configuration ':compile'.
>   > Could not find com.theoryinpractise.frege:frege:3.22.367-g2737683-g2737683.
>   oh, this is a wrong URL, therefore the trouble.

I'll have see where that comes from. looks like the native-gen pom has a wrong entry.

I agree this all looks like a lot of dependencies but the plugin is where it all comes together: frege, repl, native-gen, and the build system itself. The good news
- it is self-installing (when the URLs are correct :-))
- it is all cached locally, so no hits after first use
- dependency management is safe (unless you use SNAPSHOT versions which we only do while developing, never for releases)

cheers
Dierk

**Comment by Ingo60** [comment]
The first error I could fix, see my commit.

Still it doesn't find:

> Could not find frege:frege-repl-core:1.1.1-SNAPSHOT

(The same happens on your GUI project.)

**Comment by Ingo60** [comment]
Is it correct that one needs to build the frege-repl locally (with maven) before the gradle-plugin will do anything useful apart from not installing itself?

**Comment by Dierk** [comment]
This is probably the case - at least for the latest snapshot, which is still under development and tries to include the compiler, doc tool, quickcheck, native-gen, and repl into a single access point.
The point is that frege-repl seems not to have published it's artifacts in any public repository, yet.
We could bundle them up ourselves and have them as local jars. This would work but is kind of against the purpose of dependency management...

**Comment by Ingo60** [comment]
I understand, then we have to approach @mmhelloworld 

But how am I (as the prototypical "let's try this out" user) supposed to know this?

FInally, I fixed my local install, now lets continue with frepl-gui ...

**Comment by Dierk** [comment]
updated https://github.com/Frege/frege-gradle-plugin/blob/master/README.adoc

Does that address the issue?

**Comment by Ingo60** [comment]
Yes, much better.
