### ISSUE TITLE
build failed 2

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-gradle-plugin#8]
I was trying to install the gradle-frege-plugin locally to be able to overcome the build failures that occur from different projects (i.e. https://github.com/Dierk/frepl-gui) that use it.

After having resolved the dependency problems (see my commits and issues), the following still happened:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> frege/nativegen/Main : Unsupported major.minor version 52.0
```

I am sure this is by accident, as this probably doesn't need to be compiled with java8?

**Comment by Dierk** [comment]
I'd say that this is an issue that we have to bring up in the native-gen project.
